### ISSUE TITLE
Average Peak Finding Returning Empty Waves & Wave Leading Edge

### ISSUE THREAD

**Issue by acschick** [SeanMcGrath/fadc-tools#2]
1. Inputting 'fadc -p average analyze 7 312.root' returns thousands of entries in the Wave integral, Wave Leading Edge list. A significant number of these waves do not have peaks, and should not be considered in the analysis. Please implement an auto-veto for below-threshold waves to speed up analysis.
2. Is the number is the Wave Leading Edge column the bin number when looking at the wave?
3. Do you still have the python code from the first time we did drift time studies?

**Comment by SeanMcGrath** [comment]
Please attach/send me the root file in question

**Comment by SeanMcGrath** [comment]
Implemented an integral low-pass filter with the -m MIN_INTEGRAL flag.

usage:
fadc --min-integral 100 -p average analyze 321.root
fadc -m 100 -p average analyze 321.root

Both of these commands will print only waveforms with integral > 100
