### ISSUE TITLE
Analyze Command Not Returning Values

### ISSUE THREAD

**Issue by acschick** [SeanMcGrath/fadc-tools#3]
After installing the latest update, using the analyze function no longer appears to work properly. Using the analyze command returns empty lists for Wave integral, Wave Leading Edge. It is known that there are peaks in the ROOT file, as they can be seen and are found when using the view command. The following is the dialogue that appears in the terminal.

In[1]: fadc -p average analyze 309.root
Out[1]: Wave integral, Wave Leading Edge
Out[1]:5,2

In[2]: fadc -p average analyze 7 311.root
Out[2]: Wave integral, Wave Leading Edge

In[3]: fadc -p average analyze 7 312.root
Out[3]: Wave integral, Wave Leading Edge

**Comment by SeanMcGrath** [comment]
Please send me the root files you are using

**Comment by SeanMcGrath** [comment]
Found the source of the problem, which was actually a pretty serious bug. The integrals calculated so far have incorrect -- they should be correct going forward. Patch will be out soon.

**Comment by SeanMcGrath** [comment]
Fixed in latest commit. Also the '-p constfrac' option for constant fraction peak detection is now working well.
